#!/bin/bash
#
#  Synopsis:
#	Roll various desc logs (*.[fqx]dr) to round robin db in cache/rrd/*.rrd
#  Usage:
#	export BLOBIO_ROOT=/opt/jmscott/jmsdesk/blobio
#	* * * * * cron-dr2rdd
#  Exit Status:
#	0	ok
#	1	unexpected error
#  Note:
#	Need to add test to insure this jobs runs under a minute!
#

START_EPOCH=$(date +%s)
PROG=$(basename $0)

log()
{
	echo "$(date +'%Y/%m/%d %H:%M:%S'): $PROG#$$: $@"
}

leave()
{
	log "good bye, cruel world: elapsed $(elapsed-english $START_EPOCH)"
}

die()
{
	log "ERROR: $@" >&2
	exit 1
}

log 'hello, world'
trap leave EXIT

test $# = 0 || die "wrong number of arguments: got $#, expected 0"

test -n "$BLOBIO_ROOT" || die "env not defined: BLOBIO_ROOT"
log "BLOBIO_ROOT=$BLOBIO_ROOT"
cd $BLOBIO_ROOT || die "cd BLOBIO_ROOT failed: exit status=$?"

. etc/profile

log 'pushing all dr records to rrd ...'
bio-dr2rrd || die "bio-dr2rrd failed: exit status=$?"

log "deleting stage fdr tuples older than 3 days"
psql <<END || die "psql delete failed: exit status=$?"
DELETE FROM blobio.rrd_stage_fdr
  WHERE
  	(
		date_trunc('minute', now())
		-
		date_trunc('minute', start_time + wall_duration)
	) > '3 days'
END
