/*
 *  Synopsis:
 *	Schema to archive flow and os exec request records generated by flowd.
 *  Blame:
 *	jmscott@setspace.com
 *	setspace@gmail.com
 */
\set ON_ERROR_STOP on

set search_path to blobio,public;

begin;

drop table if exists blobio.fdr cascade;
create table fdr
(
	blob		udig
				not null,
	start_time	brr_timestamp,
	sequence	int8
				check (
					sequence > 0
				),
	ok_count	int2
				check (
					ok_count >= 0
				)
				not null,
	fault_count	int2
				check (
					fault_count >= 0
				)
				not null,
	wall_duration	brr_duration,

	insert_time	timestamp
				default now()
				not null,

	primary key	(start_time, sequence)
);
create index fdr_start_time on fdr(start_time);
create index fdr_blob on fdr(blob);
revoke update on fdr from public;

drop table if exists blobio.xdr cascade;
create table xdr
(
	start_time		brr_timestamp,
	flow_sequence		int8
					check (
						flow_sequence > 0
					)
					not null,
	call_name		text
					check (
						call_name ~
					    '^[[:alpha:]][_[:alnum:]]{0,127}$'
					)
					not null,
	blob			udig
					not null,
	termination_class	text	
					check (
						termination_class in (
							'OK',
							'ERR',
							'SIG',
							'NOPS'
						)
					),

	termination_code	int2
					check (
						termination_code >= 0
						and
						termination_code <= 255
					)
					not null,
	wall_duration		brr_duration,
	system_duration		brr_duration,
	user_duration		brr_duration,

	insert_time		timestamp
					default now()
					not null,
	primary key		(start_time, flow_sequence, call_name)
);
create index xdr_blob on xdr(blob);
revoke update on xdr from public;

commit;
