#!/usr/bin/env bash
#
#  Synopsis:
#	Hard start of flowd process from MAC OS launchd or systemd.
#  Usage:
#	export BLOBIO_ROOT=/opt/local/jmscott/jmsdesk/blobio
#	sbin/start-flowd <path/to>/blobio.flow
#  Requires:
#	gnu xargs
#  Note:
#	Ponder moving 'unset PGSYSCONFDIR' somewhere else.
#	Only gocode/libpq croaks on defined PGSYSCONFDIR, so we can
#	not put 'unset PGSYSCONFDIR' in etc/profile.
#
#		BLOBIO_ROOT=/usr/local/blobio/sync/remote/wework
#		cd $BLOBIO_ROOT
#		sbin/start-flowd etc/wework.flow
#

PROG=$(basename $0)

unset PGSYSCONFDIR			#  PGSYSCONFDIR busts golang libpq

now()
{
	date +'%Y/%m/%d %H:%M:%S'
}

log()
{
	echo "$(now): $PROG: $@"
}

ERROR()
{
	log "ERROR: $@" >&2
}

fault()
{
	ERROR "$@"
	test -d run && log "$@" >>run/$PROG.fault
}

die()
{
	fault "$@"
	exit 1
}

zap_run()
{
	test -z "$BLOBIO_ROOT" -o ! -d $BLOBIO_ROOT && return 0

	log 'removing stale files in run/flowd*'
	find run/ -type f -name 'flowd*' | xargs --no-run-if-empty rm -v
	local STATUS="${PIPESTATUS[*]}"
	if [ "$STATUS" != '0 0' ];  then
		fault "rm run/stale failed: exit status=$STATUS"
		return 1
	fi
	return 0
}

leave()
{
	STATUS=$?
	zap_run
	log 'good bye, cruel world'
	exit $STATUS
}

test $# = 1 || die "wrong number of command arguments: got $#, expected 1"
FLOW_CONF=$1
test -n "$BLOBIO_ROOT" || die 'env not defined: BLOBIO_ROOT'

log 'hello, world'
trap leave EXIT

log "BLOBIO_ROOT=$BLOBIO_ROOT"
log "PATH=$PATH"
log "flow conf: $FLOW_CONF"
log "current directory: $(pwd)"

test -r $FLOW_CONF || die "can not read flow conf: $FLOW_CONF"
test -r etc/profile || die "can not read etc/profile"
. etc/profile

#  Note: need flowd to be smarter about missing brr file!
touch spool/bio4d.brr || die "touch bio4d.brr failed: exit status=$?"

#
#  In theory, launchd or systemd is responsible for killing the kids,
#  so we can confidently clean out the run/flowd files.
#
#	<key>AbandonProcessGroup</key>
#	<false/>
#
#  However, we do not trust launchd, so simply kill a running flowd
#  and move on.
#
RUN_PID=run/flowd.pid
if [ -e $RUN_PID ];  then
	log "pid file exists: $RUN_PID"
	if [ -s $RUN_PID ];  then
		PID=$(head -1 $RUN_PID)
		log "killing possible flowd process: #$PID"
		kill $PID
	else
		log 'pid file is empty, so perhaps flowd crashed'
	fi
else
	log 'no run/flowd.pid (good)'
fi

zap_run || die 'zap_run failed'

log "invoking flowd server: $FLOW_CONF"
bin/flowd server $FLOW_CONF
log "flowd exit status: $?"
exit 0
