#!/usr/bin/env perl
#
#  Synopsis:
#	Automade script /cgi-bin//service, made by cgi2perl5.
#  Source Path:
#	service.cgi
#  Source SHA1 Digest:
#	No SHA1 Calculated
#  Note:
#	Do not make changes directly to this script.
#
die "SERVER_ROOT environment variable not defined"
				unless defined $ENV{SERVER_ROOT}
;

#
#  Prepend the $SERVER_ROOT/lib directory
#  to the load path.
#
unshift @INC, "$ENV{SERVER_ROOT}/lib";

our %CGI;

require 'httpd2.d/common.pl';
$CGI{name} = 'service';
#
#  Default content type for all elements.
#
$CGI{GET}->{out}->{'content-type'} = 'text/html';

#
#  BEGIN: /cgi/GET/out/query-args
#
$CGI{GET}->{out}->{'query-args'}->{arg}->{id} = {
	perl5_re	=>	'\w[\w-]{0,32}'
};
$CGI{GET}->{out}->{'query-args'}->{arg}->{class} = {
	perl5_re	=>	'\w[\w-]{0,32}'
};
#
#  'out' query argument must match one of the out putter names.
#
$CGI{GET}->{out}->{'query-args'}->{arg}->{out} = {
	perl5_re	=> 	'table|(?:table[.]del)|help',
	default		=>	'help',
};
#
#  BEGIN: /cgi/GET/out/putter[@name='table']
#
$CGI{GET}->{out}->{putter}->{'table'}->{name} = 'table';

#
#  BEGIN: /cgi/GET/out/putter[@name=table]/query-args
#
#
#  END: /cgi/GET/out/putter[@name='table']
#

#
#  BEGIN: /cgi/GET/out/putter[@name='table.del']
#
$CGI{GET}->{out}->{putter}->{'table.del'}->{name} = 'table.del';

#
#  BEGIN: /cgi/GET/out/putter[@name=table.del]/query-args
#
#
#  END: /cgi/GET/out/putter[@name='table.del']
#


#
#  BEGIN: /cgi/POST/in/putter[@name='post.add']
#
$CGI{POST}->{in}->{putter}->{'post.add'}->{name} = 'post.add';
$CGI{POST}->{in}->{putter}->{'post.add'}->{vars}->{var}->{srv} = {
	perl5_re	=>	'[a-z][a-z0-9_-]{0,32}',
	required	=>	'yes',
};
$CGI{POST}->{in}->{putter}->{'post.add'}->{vars}->{var}->{pghost} = {
	perl5_re	=>	'[a-z0-9][a-z0-9_.-]{0,63}',
	required	=>	'yes',
};
$CGI{POST}->{in}->{putter}->{'post.add'}->{vars}->{var}->{pgport} = {
	perl5_re	=>	'[0-9]{1,5}',
	required	=>	'yes',
};
$CGI{POST}->{in}->{putter}->{'post.add'}->{vars}->{var}->{pguser} = {
	perl5_re	=>	'[a-z0-9][a-z0-9_@-]{0,63}',
	required	=>	'yes',
};
$CGI{POST}->{in}->{putter}->{'post.add'}->{vars}->{var}->{pgdatabase} = {
	perl5_re	=>	'[a-z0-9][a-z0-9_-]{0,63}',
	required	=>	'yes',
};
$CGI{POST}->{in}->{putter}->{'post.add'}->{vars}->{var}->{blobsrv} = {
	perl5_re	=>	'[a-z0-9][a-z0-9]{0,7}:[[:graph:]]{1,127}',
	required	=>	'yes',
};
$CGI{POST}->{in}->{putter}->{'post.add'}->{vars}->{var}->{rrdhost} = {
	perl5_re	=>	'[a-z0-9][a-z0-9_.-]{0,63}',
	required	=>	'yes',
};
$CGI{POST}->{in}->{putter}->{'post.add'}->{vars}->{var}->{rrdport} = {
	perl5_re	=>	'[0-9]{1,5}',
	required	=>	'yes',
};
#
#  END: /cgi/POST/in/putter[@name=post.add]/vars
#

#
#  END: /cgi/POST/in/putter[@name='post.add']
#


#
#  BEGIN: /cgi/POST/in/putter[@name='post.del']
#
$CGI{POST}->{in}->{putter}->{'post.del'}->{name} = 'post.del';
$CGI{POST}->{in}->{putter}->{'post.del'}->{vars}->{var}->{srv} = {
	perl5_re	=>	'[a-z][a-z0-9_-]{0,32}',
	required	=>	'yes',
};
#
#  END: /cgi/POST/in/putter[@name=post.del]/vars
#

#
#  END: /cgi/POST/in/putter[@name='post.del']
#

$CGI{GET}->{out}->{putter}->{help}->{name} = 'help';
$CGI{GET}->{out}->{putter}->{help}->{'content-type'} = 'text/html';

require "httpd2.d/$ENV{REQUEST_METHOD}.pl";
