#!/bin/bash
#
#  Synopsis:
#	Exec a login bash shell with BLOBIO_ROOT set to $1
#  Usage:
#	BLOBIO_ROOT-bash /opt/jmscott/jmsdesk/blobio
#	alias 2jmsdesk='BLOBIO_ROOT-bash /opt/jmscott/jmsdesk/blobio'
#

die()
{
	echo "ERROR: $@" >&2
	exit 1
}

WARN()
{
	echo "WARN: $@" >&2
}

test $# = 1 || die "wrong number of arguments: got $#, expected 1"
export BLOBIO_ROOT=$1
echo
echo "BLOBIO_ROOT=$BLOBIO_ROOT"

cd $BLOBIO_ROOT || die "cd failed: $BLOBIO_FAILED"
test -r etc/bash_login || die 'can not read etc/bash_login'

exec bash --init-file etc/bash_login --noprofile
