#!/bin/bash
#
#  Synopsis:
#	Reboot blobio servers (not cron) into cleanish development environment.
#  Description:
#	The script 'dev-reboot' establishes a clean development environment.
#	for the biod and flowd	servers.  Cronjobs are NOT reset.
#
#	Before rebooting all blobio servers, the script dev-reboot kills
#	biod and flowd processes owned by $USER, copies the example templates
#	for profile, blobio.flow and psqlrc files into the directory etc/, and
#	the removes all files the directories in spool/, log/ and run/.
#
#	Since etc/profile is rewritten to the default in lib/profile.example,
#	the script MUST start in the same directory as the directory
#	determined by BLOBIO_ROOT in lib/profile.example.
#	
#  Usage:
#	cd $HOME/opt/blobio
#	. bash_login
#	dev-reboot >dev-reboot.out 2>&1 &
#  Note:
#	Simulating cron jobs is tricky.  Investigate integrating with anacron.
#

PROG=$(basename $0)

log()
{
	echo "$(date +'%Y/%m/%d %H:%M:%S'): $PROG#$$: $@"
}

die()
{
	log "ERROR: $@" >&2
	exit 1
}

leave()
{
	log 'good bye, cruel world'
}

reset_etc()
{
	log 'resting configs in directory etc/'
	while [ "$1" ];  do
		F="$1"
		shift

		LF=lib/$F.example
		test -r $LF			|| die "can not read file: $LF"

		EF=etc/$F

		log "copy $LF -> $EF"
		rm -f $EF			|| die "rm -f $EF failed"
		cp $LF $EF			|| die "cp $LF $EF failed"
		chmod +w $EF			|| die "chmod $EF failed"
	done
}

log 'hello, world'
trap leave EXIT

log "killing processes owned by $USER: biod flowd"
pkill -u $USER biod flowd

log 'zap files in directories: run/ spool/ log/'
(
	echo bloody-bsd-xargs-missing-no-run-if-empty
	find run spool log -type f 					|
		#  don't zap log/dev-reboot.lo
		fgrep -v log/dev-reboot.log

) | xargs rm -vf

reset_etc profile psqlrc blobio.flow || exit 1
cron-reboot
