#!/bin/bash
#
#  Synospsis:
#	Report of running bio4d & flowd processes.
#  Usage:
#	run-stat-report
#  See:
#	/usr/local/jmscottsbin/run-stat
#	https://github.com/jmscott/work
#  Exit Status:
#	0	ok
#	1	error
#  Note:
#	On gnu/linux sort is ignoring the second key.  The pain never ends.
#
#	Rename this script to run-pid-report?
#
NOW=$(date +'%s')

die()
{
	echo "$(basename $0): ERROR: $@" >&2
	exit 1
}

(
	echo 'Process	Status	Up Time	Boot Request,Ok,Fail	Recent 10s Sample'
	echo '-------	------	-------	-------------------	-----------------'
	run-stat							|
		sort --key=2 --key=1 --field-separator=$'\t'		|
		while read PID STATUS START_EPOCH			\
		           FDR OK FLT WALL				\
		           sFDR sOK sFLT sWALL				\
			   ;  do
			case "$START_EPOCH" in
			[0-9]*)
				DURATION=$(duration-english $(
					expr $NOW - $START_EPOCH
				))
				;;
			UNKNOWN)
				DURATION=UNKNOWN
				;;
			esac
			echo "$PID	$STATUS	$DURATION	$FDR,$OK,$FLT	$sFDR,$sOK,$sFLT"
		done
		
)									|
	sed 's/,,/?/g'							|
	column -s '	' -t						|
	sed 's/ *	//'
