#!/bin/bash
#
#  Synopsis:
#	Lock a udig in a flow particular flow.
#  Usage:
#	#  invoked in etc/blobio.flow
#	lock-flow-udig <udig>
#  Exit Status:
#      0  -  no lock exists, so create lock file in run/flowd-<udig>.lock
#      1  -  lock already exists
#      2  -  unexpected error
#  See:
#	https://github.com/jmscott/work/blob/master/tas-unlock-fs.c
#

test $# = 0 && exec tas-unlock-fs "run/flowd-$1.lock"
echo "$(basename $0): ERROR: wrong number of args: got $#, expected 1" >&2
exit 2
