#!/usr/bin/env bash
#
#  Synopsis:
#	Calculate SHA1 digest standard input or list of files using OpenSSL.
#  Usage:
#	echo hello, world | bio-sha
#	bio-sha *.c
#  Exit Status:
#	0	no errors
#	1	errors occured, failing on first error
#

case $# in
0)
	openssl dgst -sha1 | sed 's/.*= *//'
	test "${PIPESTATUS[*]}" = '0 0' || exit 1
	;;
*)
	for F in $@;  do
		openssl dgst -sha1 "$F" | sed 's/.*= *//'
		test "${PIPESTATUS[*]}" = '0 0' || exit 1
	done
esac

exit 0
