#!/bin/bash
#
#  Synopsis:
#	Eat a stream of blobs from either the command line or standard input
#  Exit Status:
#	0	all blob request to eat suceeded, both existing or not
#	1	request to eat a blob failed, some blobs may not be digested
#  Environment:
#	BLOBIO_SERVICE
#  Usage:
#	bio-eat <large.udig
#	bio-eat sha:7884029948e18cb1f5d442a46b7721d0178ccc39 ...
#	xargs bio-eat <large.udig
#  Blame:
#  	jmscott@setspace.com
#	setspace@gmail.com
#  Note:
#	Think about a script called bio-digest which eats a local file.
#
PROG=$(basename $0)
SERVICE=${BLOBIO_EAT_SERVICE:=$BLOBIO_SERVICE}

die()
{
	echo "$PROG: ERROR: $@" >&2
	exit 1
}

bio_eat()
{
	UDIG="$1"

	blobio eat --udig $UDIG --service $SERVICE
	STATUS=$?
	case $STATUS in
	0)
		echo "=$UDIG"
		;;
	1)
		echo "?$UDIG"
		;;
	*)
		die "blobio eat $UDIG failed: exit status=$STATUS: "
		;;
	esac
}

case $# in
0)
	while read LINE;  do
		bio_eat "$LINE"
	done
	;;
*)
	#
	#  Read blobs from the command line.
	#
	while [ "$1" ]; do
		bio_eat "$1"
		shift
	done
	;;
esac
