#!/bin/bash
#
#  Synopsis:
#	Put files to blobio server.
#  Usage:
#	bio-put <file1> <file2> ...
#	find . -type f -print | bio-put
#  Blame:
#  	jmscott@setspace.com
#	setspace@gmail.com
#

PROG=$(basename $0)
ALGORITHM=sha
SERVICE=${BLOBIO_SERVICE:=localhost:1797}

die()
{
	echo "$PROG: $@" >&2
	exit 1
}

put_file()
{
	FILE="$1"

	test -d "$FILE" && die "$FILE is a directory"
	test -r "$FILE" || die "can't read file $FILE"
	DIGEST=$(blobio eat --algorithm $ALGORITHM --input-path "$FILE")
	STATUS=$?
	test -n "$DIGEST" -o $STATUS != 0 || die "blobio eat failed"
	UDIG=$ALGORITHM:$DIGEST
	blobio eat --udig $UDIG --service $SERVICE
	STATUS=$?
	case $STATUS in
	1)
		blobio put --udig $UDIG --input-path "$FILE" --service $SERVICE
		test $? = 0 || die "blobio put failed: $FILE"
		cat <<END
$FILE
	>$UDIG
END
		;;
	0)
		cat <<END
$FILE
	@$UDIG
END
		;;
	*)
		die "blobio eat: unexpected exit status"
		;;
	esac
}

case $# in
0)
	while read F;  do
		put_file "$F"
	done
	;;
*)
	while [ "$1" ];  do
		put_file "$1"
		shift
	done
	;;
esac
