#!/bin/bash
#
#  Synopsis:
#	Put a file meta blob and the file itself as a blob
#  Blame:
#  	jmscott@setspace.com
#	setspace@gmail.com
#  Note:
#	Very large blobs give no feedback while calculating the digest,
#	which can be confusing.
#

PROG=$(basename $0)
ALGORITHM=sha
SERVICE=${BLOBIO_SERVICE:=localhost:1797}
TMPDIR=${TMPDIR:=/tmp}
JSON=$TMPDIR/$PROG-$$.json

trap "rm -f $JSON" EXIT

die()
{
	echo "$PROG: $@" >&2
	exit 1
}

escape_json()
{
	perl -p -e 's/([\\"])/\\$1/g'			|
		perl -p -e 's/\n/\\n/g'			|
		perl -p -e 's/\t/\\t/g'			|
		perl -p -e 's/[\b]/\\b/g'		|
		perl -p -e 's/\f/\\f/g'			|
		perl -p -e 's/\r/\\r/g'
}

put_file()
{
	FILE="$1"

	test -d "$FILE" && die "$FILE is a directory"
	test -r "$FILE" || die "can't read $FILE"

	DIGEST=$(blobio eat --algorithm $ALGORITHM --input-path "$FILE")
	test -n "$DIGEST" || die "blobio eat failed"
	UDIG=$ALGORITHM:$DIGEST
	blobio eat --udig $UDIG --service $SERVICE
	STATUS=$?
	case $STATUS in
	1)
		blobio put --udig $UDIG --input-path "$FILE" --service $SERVICE
		test $? = 0 || die "blobio put failed: $FILE"
		cat <<END
$FILE
	>$UDIG
END
		;;
	0)
		cat <<END
$FILE
	@$UDIG
END
		;;
	*)
		die "blobio eat: unexpected exit status: $FILE"
		;;
	esac

	#
	#  Put the json meta description
	#
	cat <<END >$JSON
{
	"blobio": {
		"command-line": {
			"command":	"bio-put-file",
			"udig":		"$UDIG",
			"path":		"$(echo -n $FILE | escape_json)"
		},
		"hostname":	"$(hostname)",
		"env": 		{
					"USER":	"$USER"
		},
		"gnu-file":	"$(file $FILE | escape_json)",
		"date":		"$(date)",
		"stat":		"$(stat $FILE | escape_json)"
	}
}
END
	test -s $JSON || die "file has size of zero: $JSON"

	DIGEST=$(blobio eat --algorithm $ALGORITHM --input-path $JSON)
	test -n "$DIGEST" || die "blobio eat failed: $JSON"
	UDIG=$ALGORITHM:$DIGEST
	blobio eat --udig $UDIG --service $SERVICE
	STATUS=$?
	case $STATUS in
	1)
		blobio put --udig $UDIG --input-path $JSON --service $SERVICE
		test $? = 0 || die "blobio put failed: $JSON"
		cat <<END
	>>$UDIG
END
		;;
	0)
		cat <<END
	@@$UDIG
END
		;;
	*)
		die "blobio eat: unexpected exit status: $JSON"
		;;
	esac
}

case $# in
0)
	while read F;  do
		put_file "$F"
	done
	;;
*)
	while [ "$1" ];  do
		put_file "$1"
		shift
	done
	;;
esac
