#!/usr/bin/env bash
#
#  Synopsis:
#	Cancatenate a list of blobs given on the command line
#  Usage:
#	bio-cat <udig1> [udig2 ...]
#	bio-cat sha:a0bc76c479b55b5af2e3c7c4a4d2ccf44e6c4e71
#  Environment:
#	BLOBIO_SERVICE
#	BLOBIO_GET_SERVICE
#
PROG=$(basename $0)

die()
{
	echo "$PROG: ERROR: $@" >&2
	exit 1
}

test -n "$BLOBIO_SERVICE" || die 'env variable not defined: BLOBIO_SERVICE'
SERVICE=${BLOBIO_GET_SERVICE:=$BLOBIO_SERVICE}

while [ "$1" ]; do
	UDIG="$1"

	#
	#  Fetch the file from the blob server.
	#
	blobio get --udig "$UDIG" --service $SERVICE
	STATUS=$?
	case $STATUS in
	0)
		;;
	1)
		die "no such blob: $UDIG"
		;;
	*)
		die "blobio get $UDIG $SERVICE failed: exit status=$STATUS"
		;;
	esac
	shift
done
