#!/bin/bash
#
#  Synopsis:
#	Unix 'file' command run on a blob
#  Blame:
#  	jmscott@setspace.com
#	setspace@gmail.com
#
PROG=$(basename $0)
SERVICE=${BLOBIO_GET_SERVICE:=$BLOBIO_SERVICE}
ALGORITHM=sha
TMP_FILE=${TMPDIR:=/tmp}/$PROG.$$

die()
{
	echo "$PROG: ERROR: $@" >&2
	exit 1
}

leave()
{
	STATUS=$?
	rm -f $TMP_FILE
	exit $STATUS
}

trap leave EXIT

while [ "$1" ]; do
	UDIG="$1";  shift

	rm -f $TMP_FILE || die "rm -f $TMP_FILE failed: eit status=$?"

	blobio get --udig $UDIG --service $SERVICE --output-path $TMP_FILE
	STATUS=$?
	case "$STATUS" in
	0)
		;;
	1)
		echo "?$UDIG"
		continue
		;;
	*)
		die "blob get $UDIG $SERVICE failed"
		;;
	esac
	echo ">$UDIG	$(file --brief $TMP_FILE | sed 's/	/ /g')"
done
