#!/bin/bash
#
#  Synopsis:
#	Put both the file and a json meta blob to the blob service.
#  Usage:
#	bio-put-file invoice-20160215.pdf
#	find . -name '*.pdf' -print | bio-put-file
#

PROG=$(basename $0)
TMPDIR=${TMPDIR:=/tmp}
JSON=$TMPDIR/$PROG-$$.json

trap "rm -f $JSON" EXIT

die()
{
	echo "$PROG: $@" >&2
	exit 1
}

test -n "$BLOBIO_SERVICE" || die 'env variable not defined: BLOBIO_SERVICE'
test -n "$BLOBIO_ALGORITHM" || die 'env variable not defined: BLOBIO_ALGORITHM'

escape_json()
{
	perl -p -e 's/([\\"])/\\$1/g'			|
		perl -p -e 's/\n/\\n/g'			|
		perl -p -e 's/\t/\\t/g'			|
		perl -p -e 's/[\b]/\\b/g'		|
		perl -p -e 's/\f/\\f/g'			|
		perl -p -e 's/\r/\\r/g'
}

put_file()
{
	FILE="$1"

	test -d "$FILE" && die "$FILE is a directory"
	test -r "$FILE" || die "can't read $FILE"

	DIGEST=$(blobio eat --algorithm $BLOBIO_ALGORITHM --input-path "$FILE")
	test -n "$DIGEST" || die "blobio eat failed"
	UDIG=$BLOBIO_ALGORITHM:$DIGEST
	blobio eat --udig $UDIG --service $BLOBIO_SERVICE
	STATUS=$?
	case $STATUS in
	1)
		blobio put --udig $UDIG --input-path "$FILE" 		\
						--service $BLOBIO_SERVICE
		test $? = 0 || die "blobio put failed: $FILE"
		cat <<END
$FILE
	>$UDIG
END
		;;
	0)
		cat <<END
$FILE
	@$UDIG
END
		;;
	*)
		die "blobio eat: unexpected exit status: $FILE"
		;;
	esac

	#
	#  Put the json meta description
	#
	cat <<END >$JSON
{
	"blobio.com": {
		"command-line": {
			"command":	"bio-put-file",
			"udig":		"$UDIG",
			"path":		"$(echo -n "$FILE" | escape_json)",
			"pwd":		"$(pwd | escape_json)"
		},
		"hostname":	"$(hostname)",
		"environment": 		{
					"USER":	"$USER",
					"LOGNAME":	"$LOGNAME"
		},
		"gnu-file":	"$(file "$FILE" | escape_json)",
		"date":		"$(date)",
		"stat":		"$(stat "$FILE" | escape_json)"
	}
}
END
	test -s $JSON || die "file has size of zero: $JSON"

	DIGEST=$(blobio eat --algorithm $BLOBIO_ALGORITHM --input-path $JSON)
	test -n "$DIGEST" || die "blobio eat failed: $JSON"
	UDIG=$BLOBIO_ALGORITHM:$DIGEST
	blobio eat --udig $UDIG --service $BLOBIO_SERVICE
	STATUS=$?
	case $STATUS in
	1)
		blobio put --udig $UDIG --input-path $JSON 		\
				--service $BLOBIO_SERVICE
		test $? = 0 || die "blobio put failed: $JSON"
		cat <<END
	>>$UDIG
END
		;;
	0)
		cat <<END
	@@$UDIG
END
		;;
	*)
		die "blobio eat: unexpected exit status: $JSON"
		;;
	esac
}

case $# in
0)
	while read F;  do
		put_file "$F"
	done
	;;
*)
	while [ "$1" ];  do
		put_file "$1"
		shift
	done
	;;
esac
