#!/bin/bash
#
#  Synopsis:
#	Give files to blobio server, deleting them locally.
#  Usage:
#	bio-give <file1> <file2> ...
#	find . -type f -print | bio-give
#  Blame:
#  	jmscott@setspace.com
#	setspace@gmail.com
#

PROG=$(basename $0)
ALGORITHM=${BLOBIO_ALGORITHM:=sha}

die()
{
	echo "$PROG: $@" >&2
	exit 1
}

test -n "BLOBIO_SERVICE" || die 'env variable not defined: BLOBIO_SERVICE'

give_file()
{
	FILE="$1"

	test -d "$FILE" && die "$FILE is a directory"
	test -r "$FILE" || die "can't read $FILE"
	DIGEST=$(blobio eat --algorithm $ALGORITHM --input-path "$FILE")
	test -n "$DIGEST" || die "blobio eat failed"
	UDIG=$ALGORITHM:$DIGEST
	#
	#  Verify if the blob exists.
	#
	blobio eat --udig $UDIG --service $BLOBIO_SERVICE
	STATUS=$?
	case $STATUS in
	1)
		#
		#  Give the new blob
		#
		blobio give --udig $UDIG --input-path "$FILE" 		\
			--service $BLOBIO_SERVICE
		STATUS=$?
		test $STATUS = 0 ||
			die "blobio give failed: exit status=$STATUS: $FILE"
		cat <<END
$FILE
	>$UDIG
END
		;;
	0)
		cat <<END
$FILE
	@$UDIG
END
		unlink "$FILE" || die "unlink $FILE failed"
		;;
	*)
		die "blobio eat: unexpected exit status: $STATUS"
		;;
	esac
	cat <<END
	-$FILE
END
}

case $# in
0)
	while read F;  do
		give_file "$F"
	done
	;;
*)
	while [ "$1" ];  do
		FILE=
		ARG="$1"
		shift
		case "$ARG" in
		'')
			die 'empty argument'
			;;
		--*)
			die "unknown option: $ARG"
			;;
		*)
			FILE="$ARG"
			;;
		esac
		test -n "$FILE" && give_file "$FILE"
	done
	;;
esac
