#!/bin/bash
#
#  Synopsis:
#	Unix 'file' command run on a blob
#  Blame:
#  	jmscott@setspace.com
#	setspace@gmail.com
#
PROG=$(basename $0)
ALGORITHM=${BLOBIO_ALGORITHM:=sha}
TMP_FILE=${TMPDIR:=/tmp}/$PROG.$$

die()
{
	echo "$PROG: ERROR: $@" >&2
	exit 1
}

leave()
{
	STATUS=$?
	rm -f $TMP_FILE
	exit $STATUS
}

trap leave EXIT

test -n "$BLOBIO_SERVICE" || die 'env variable not defined: BLOBIO_SERVICE'

while [ "$1" ]; do
	UDIG="$1";  shift

	rm -f $TMP_FILE || die "rm -f $TMP_FILE failed: eit status=$?"

	blobio get 							\
		--udig $UDIG						\
		--output-path $TMP_FILE					\
		--service $BLOBIO_SERVICE
	STATUS=$?
	case "$STATUS" in
	0)
		;;
	1)
		echo "?$UDIG"
		continue
		;;
	*)
		die "blob get $UDIG $BLOBIO_SERVICE failed"
		;;
	esac
	echo ">$UDIG	$(file --brief $TMP_FILE | sed 's/	/ /g')"
done
