#!/usr/bin/env bash
#
#  Synopsis:
#	Make the root dir tree for a remote service in $BLOBIO_ROOT/sync/remote
#  Usage:
#	make-sync-remote <remote tag> <remote blobio service>
#	make-sync-remote lct bio4:10.187.1.2:1797
#  Note:
#	The links back to $BLOBIO_ROOT/{bin,sbin,lib} should relative!
#

die()
{
	echo "ERROR: $@" >&2
	exit 1
}

_mkdir()
{
	D=$1
	test -e $D && return 
	mkdir -p $D || die "mkdir $D failed: exit status=$?"
	chmod u=rwx,g=rx,o= $D || die "chmod $D failed: exit status=$?"
}

_ln_root()
{
	DIR=../../../$1
	TGT=$(dirname $1)
	ln --symbolic --relative $DIR $TGT				||
				die "ln -s $DIR $TGT failed: exit status=$?"
}

test $# = 1 || die "wrong number of arguments: got $#, expected 1"
REMOTE_TAG="$1"

test -n "$BLOBIO_ROOT" || die 'env not defined: BLOBIO_ROOT'

cd $BLOBIO_ROOT || die "cd $BLOBIO_ROOT failed: exit status=$?"

#  make sync directories and symlinks to $BLOBIO_ROOT

SYNC_ROOT=$BLOBIO_ROOT/sync/remote/$REMOTE_TAG
test -d $SYNC_ROOT && die "refuse to overwrite remote dir: $SYNC_ROOT"
_mkdir $SYNC_ROOT

cd $SYNC_ROOT || die "cd $SYNC_ROOT failed: exit status=$?"
_mkdir etc
_mkdir log
_mkdir run
_mkdir spool
_mkdir data
>$SYNC_ROOT/spool/bio4d.brr						||
	die "echo >spool/bio4d.brr failed: exit status=$?"
_mkdir tmp

_ln_root sbin
_ln_root bin
_ln_root lib

#  link the fs blobs but NOT the other files in data/, such as flowd.[qxf]dr
_ln_root data/fs_*

#  build a default flow file from the example file in
#  $BLOBIO_ROOT/lib/sync-remote.flow.example .

FLOW=etc/sync-$REMOTE_TAG.flow

FLOW_EXAMPLE=$BLOBIO_ROOT/lib/sync-remote.flow.example
test -r $FLOW_EXAMPLE || die "can not read flow example: $FLOW_EXAMPLE"
cp --force --verbose $FLOW_EXAMPLE $FLOW				||
		die "cp flow.example -> etc/ failed: exit status=$?"
chmod u=rw,g=r,o= $FLOW || die "chmod etc/flow failed: exit status=$?"

#  default profile just dots in local profile and resets BLOBIO_ROOT

cat >etc/profile <<END || die "cat >etc/profile failed: exit status=$?"
. ../../../etc/profile
export BLOBIO_ROOT=../../..
END
chmod u=rw,g=r,o= etc/profile || die "chmod etc/profile failed: exit status=$?"

cat <<END

Important:
	Update root service in remote flow file

		$SYNC_ROOT/$FLOW

	Also, to get request records from root to remote, update 

		$BLOBIO_ROOT/etc/blobio.flow

	to append request records from

		$BLOBIO_ROOT/spool ->

		$SYNC_ROOT/spool

END

exit 0
