#!/bin/bash
#
#  Synopsis:
#	Make the sync directory for a remote service in $BLOBIO_ROOT/sync/root
#  Usage:
#	make-sync-root <remote name> <remote blobio service>
#
#	make-sync-root lct bio4:10.187.1.2:1797
#

die()
{
	echo "ERROR: $@" >&2
	exit 1
}

_mkdir()
{
	D=$1
	test -e $D && return 
	mkdir -p $D || die "mkdir $D failed: exit status=$?"
	chmod u=rwx,g=rx,o= $D || die "chmod $D failed: exit status=$?"
}

_ln_root()
{
	S=$1
	DIR=$BLOBIO_ROOT/$S
	test -e $S && return
	test -h $S && die "invalid symbolic link: $(pwd)/$S"
	ln -s $DIR . || die "ln -s $DIR . failed: exit status=$?"
}

test $# = 2 || die "wrong number of arguments: got $#, expected 2"
REMOTE_NAME="$1"
REMOTE_BLOBIO_SERVICE="$2"
case "$REMOTE_BLOBIO_SERVICE" in
'')
	die 'empty remote blobioservice'
	;;
fs:*)
	;;
bio4:*:[0-9]*)
	;;
*)
	die "unknown blobio service: $REMOTE_BLOBIO_SERVICE"
	;;
esac

test -n "$BLOBIO_ROOT" || die 'env not defined: BLOBIO_ROOT'

cd $BLOBIO_ROOT || die "cd $BLOBIO_ROOT failed: exit status=$?"

#  make sync directories
SYNC_ROOT=$BLOBIO_ROOT/sync/root/$REMOTE_NAME
_mkdir $SYNC_ROOT
cd $SYNC_ROOT || die "cd $SYNC_ROOT failed: exit status=$?"
_mkdir log
_mkdir run
_mkdir etc
_mkdir tmp

_ln_root sbin
_ln_root spool
_ln_root bin
_ln_root lib

#  build a default flow file from the example file in
#  $BLOBIO_ROOT/lib/sync-remote.flow.example .

FLOW=etc/sync-$REMOTE_NAME.flow

FLOW_EXAMPLE=$BLOBIO_ROOT/lib/sync-remote.flow.example
test -r $FLOW_EXAMPLE || die "can not read flow example: $FLOW_EXAMPLE"
sed "s/{REMOTE_BLOBIO_SERVICE}/$REMOTE_BLOBIO_SERVICE/g" $FLOW_EXAMPLE	|
	sed "s/{BLOBIO_SERVICE}/$BLOBIO_SERVICE/g"			\
	>$FLOW
STATUS=${PIPESTATUS[*]}
test "$STATUS" = '0 0' ||
	die "sed example >$FLOW failed: exit status=$STATUS"

#  default profile just dots in local profile and resets BLOBIO_ROOT

cat >etc/profile <<END || die "cat >etc/profile failed: exit status=$?"
. ../../../etc/profile
export BLOBIO_ROOT=$SYNC_ROOT
END

exit 0
