#!/bin/bash
#
#  Synopsis:
#	Start/stop blobio daemon.
#

PROG=$(basename $0)
PAUSE=3

die()
{
	log "ERROR: $@" >&2
	exit 1
}

log()
{
	if [ -z "$ACTION" ];  then
		echo "$PROG: $@"
	else
		echo "$PROG: $ACTION: $@"
	fi
}

WARN()
{
	log "WARN: $@"
}

ACTION="$1"
case "$BLOBIO_ROOT" in
'')
	die 'not defined: BLOBIO_ROOT environment variable'
	;;
*)
	test ! -d $BLOBIO_ROOT && die "not a directory: $BLOBIO_ROOT"
	log "BLOBIO_ROOT=$BLOBIO_ROOT"
	;;
esac

cd $BLOBIO_ROOT || die "cd $BLOBIO_ROOT failed"
BIOD=$BLOBIO_ROOT/sbin/biod
test -r etc/profile && . etc/profile
PORT=${BLOBIO_BIOD_PORT:=1797}
PID=$BLOBIO_ROOT/run/biod.pid

#  duration in seconds to write rrd samples to log/biod-rrd.log.
#  0 disables.
RRD_SAMPLE_DURATION=${BLOBIO_RRD_SAMPLE_DURATION:=0}

case "$ACTION" in
boot)
	rm -f $PID
	;;
start)
	PID_FILE=run/biod.pid
	if [ -f $PID_FILE ];  then
		log "is biod already running with pid #$(cat $PID_FILE)?" >&2
		die "remove file: $PID_FILE"
	fi
	$BIOD --ps-title-XXXXXXXXXXXXXXXXXXXXXXX --port $PORT		\
				--rrd-sample-duration $RRD_SAMPLE_DURATION
	STATUS=$?
	test $STATUS = 0 || die "biod failed to start: exit status=$STATUS"

	log "pausing $PAUSE seconds while biod starts ..."
	sleep $PAUSE
	test -f $PID_FILE || die "no pid file $PID_FILE, so biod aborted"
	log "started with pid #$(cat $PID_FILE)"
	log 'tail of log file follows ...'
	tail log/biod-$(date +'%a').log
	;;
stop)
	zap-proc run/biod.pid
	;;
reboot)
	zap-proc run/biod.pid
	biod_ctl start
	;;
restart)
	log 'restart'
	$0 stop
	$0 start
	;;
'')
	die 'missing expected action: start|stop|restart|reboot'
	;;
*)
	ACTION=
	die "unknown action: expected start|stop|restart|reboot"
	;;
esac
exit 0;
