#!/bin/sh
#
#  Synopsis:
#	Create the round robin database for blobio.
#  Blame:
#  	jmscott@setspace.com
#  	setspace@gmail.com
#

PROG=$(basename $0)
RRD=log/biod.rrd
START=1392491400
STEP=15
HBEAT=30
MAX=4294967295

die()
{
	echo "$PROG: ERROR: $@" >&2
	exit 1
}

test "$BLOBIO_ROOT" || die 'env variable not defined: BLOBIO_ROOT'
cd $BLOBIO_ROOT || die "cd $BLOBIO failed"

test -f $RRD && die "refused to overwrite rrd file: $RRD"

rrdtool create $RRD                                     		\
        --step $STEP                                       		\
        --start $START                                  		\
	DS:success:DERIVE:$HBEAT:0:$MAX					\
	DS:error:DERIVE:$HBEAT:0:$MAX					\
	DS:timeout:DERIVE:$HBEAT:0:$MAX					\
	DS:signal:DERIVE:$HBEAT:0:$MAX					\
	DS:fault:DERIVE:$HBEAT:0:$MAX					\
	DS:get:DERIVE:$HBEAT:0:$MAX					\
	DS:put:DERIVE:$HBEAT:0:$MAX					\
	DS:give:DERIVE:$HBEAT:0:$MAX					\
	DS:take:DERIVE:$HBEAT:0:$MAX					\
	DS:eat:DERIVE:$HBEAT:0:$MAX					\
	DS:wrap:DERIVE:$HBEAT:0:$MAX					\
	DS:roll:DERIVE:$HBEAT:0:$MAX					\
	DS:chat_ok:DERIVE:$HBEAT:0:$MAX					\
	DS:chat_no:DERIVE:$HBEAT:0:$MAX					\
	DS:chat_no2:DERIVE:$HBEAT:0:$MAX				\
	DS:chat_no3:DERIVE:$HBEAT:0:$MAX				\
	DS:eat_no:DERIVE:$HBEAT:0:$MAX					\
	DS:take_no:DERIVE:$HBEAT:0:$MAX					\
	RRA:LAST:0.5:1:40320						\
	RRA:MAX:0.5:1:40320						\
	RRA:AVERAGE:0.5:20:8640						\
        RRA:AVERAGE:0.5:240:8760
