#!/bin/bash
#
#  Synopsis:
#	Reboot the flowd sync processes for hosts in $BLOBIO_ROOT/sync/host
#  Usage:
#	#  Standalone
#	export BLOBIO_ROOT=/usr/local/blobio
#	reboot-sync
#
#	#  From cron-reboot
#	reboot-sync
#
PKILL_USER=$(id -un)

log()
{
	echo "$(date +'%Y/%m/%d %H:%M:%S'): $@"
}

die()
{
	log "ERROR: $@" >&2
	exit 1
}

log 'hello, world'
trap 'log good bye, cruel world' EXIT

log "BLOBIO_ROOT: $BLOBIO_ROOT"

cd $BLOBIO_ROOT || die "cd $BLOBIO_ROOT failed: exit status=$?"

if [ ! -e sync/host ];  then
	log "creating sync directory: $(pwd)/sync/host"
	mkdir -p sync/host || die "mkdir failed: $(pwd)/sync/host"
fi

logh()
{
	log "$HOST: $@"
}

dieh()
{
	die "$HOST: $@"
}

find $BLOBIO_ROOT/sync/host/ -mindepth 1 -maxdepth 1 -type d 		|
  while read SYNC_ROOT;  do
	HOST=$(basename $SYNC_ROOT)
	log "sync host: $HOST"
	cd $SYNC_ROOT || dieh "cd $SYNC_ROOT failed: exit status=$?"

	zap-proc run/flowd.pid || dieh "zap-proc flowd failed: exit status=$?"
	log "starting sync flowd server: $HOST ..."
	log "BLOBIO_ROOT for sync flowd: $SYNC_ROOT"
	BLOBIO_ROOT=$SYNC_ROOT flowd server etc/sync-$HOST.flow &
	FLOWD_PID=$!
	log "flowd process id: $FLOWD_PID"
	echo $FLOWD_PID >run/flowd.pid ||
		die "echo $FLOWD_PID >run/flowd.pid failed: exit status=$?"
done
