#!/usr/bin/perl
#
#  Synopsis:
#	Convert udigs to file system path
#  Usage:
#	grep '^[a-z][a-z]*:' WRAP_SET | udig2fs
#	udig2fs sha:781a4c9f5c135624ffda47ae7408f83f23f9e795
#

my $algo_re = '(sha|bc160)';
my $digest_re = '([0-9a-f])'		.
             '([0-9a-f]{2})'		.
	     '([0-9a-f]{4})'		.
	     '([0-9a-f]{8})'		.
	     '([0-9a-f]{16})'		.
	     '([0-9a-f]{10})'
;

if (@ARGV == 0) {
	while (<STDIN>) {
		die "unknown udig: $_" unless m/^${algo_re}:${digest_re}$/;
	}
}
