#!/usr/bin/env bash
#
#  Synopsis:
#	Start/stop bio4d daemon.
#  Usage:
#	bio4d_ctl [stop|start|restart]
#  Exit Status:
#	0	success
#	1	fault
#

PROG=$(basename $0)
PAUSE=3

#  how long to pause before hard stop of bio4d
BIO4D_STOP_PAUSE=20

die()
{
	log "ERROR: $@" >&2
	exit 1
}

log()
{
	_A="$PROG: "
	if [ -n "$ACTION" ];  then
		_A="$_A$ACTION: "
	fi
	echo "$(date +'%Y/%m/%d %H:%M:%S'): $_A$@"
	
}

case "$1" in
'')
	die 'empty action'
	;;
start|stop|restart)
	ACTION="$1"
	;;
*)
	die "unknown action: $1";
	;;
esac

case "$BLOBIO_ROOT" in
'')
	die 'not defined: BLOBIO_ROOT environment variable'
	;;
*)
	test ! -d $BLOBIO_ROOT && die "not a directory: $BLOBIO_ROOT"
	log "BLOBIO_ROOT=$BLOBIO_ROOT"
	;;
esac

cd $BLOBIO_ROOT || die "cd $BLOBIO_ROOT failed"

case "$ACTION" in
start)
	log 'boot biod4 into background ...'
	sbin/boot-bio4d $BLOBIO_ROOT &

	log "pausing $PAUSE sec while bio4d starts ..."
	sleep $PAUSE
	test -s run/bio4d.pid || die 'bio4d did not start'
	log "process id of bio4d: $(head -1 run/bio4d.pid)"
	;;
stop)
	sbin/kill-bio4d
	;;
restart)
	#
	#  since no "--mode fast" exists, we first attempt quick stop.
	#  if bio4d still running, then do a sleep a bit before restarting.
	#
	log 'restart'
	bio4d_ctl stop
	sleep 3
	BIO4D_MAY_BE_BUSY=$(test -e run/bio4d.pid;  echo $?)
	(
		(
			test $BIO6D_MAY_BE_BUSY = 0			&&
			(
				log "pause $BIO4D_STOP_PAUSE sec for socket"
				sleep $BIO4D_STOP_PAUSE
			)
			true
		)							&&
		bio4d_ctl start
	) || die 'stop/start failed, bye'

	. etc/profile
	log 'our work here is done'
	;;
*)
	die "impossible action: $ACTION"
	;;
esac
exit 0;
