#!/bin/bash
#
#  Synopsis:
#	Boot bio4d daemon, extracting properties from etc/profile
#  Usage:
#	boot-bio4d $BLOBIO_ROOT
#

PROG=$(basename $0)

log()
{
	echo "$(date +'%Y/%m/%d %H:%M:%S'): $PROG: $@"
}

die()
{
	log "ERROR: $@" >&2
	exit 1
}

zap_run()
{
	test -z "$BLOBIO_ROOT" -o ! -d $BLOBIO_ROOT && return

	log 'removing stale files in run/bio4d*'
	find run/ -type f -name 'bio4d*' | xargs --no-run-if-empty rm -v
	local STATUS="${PIPESTATUS[*]}"
	test "$STATUS" = '0 0'					||
		log "WARN: rm run/stale failed: exit status=$STATUS" >&2
}

leave()
{
	STATUS=$?
	zap_run
	log 'good bye, cruel world'
	exit $STATUS
}

test $# = 1 || die "wrong number of arguments: got $#, expected 1"

log 'hello, world'
trap leave EXIT

export BLOBIO_ROOT="$1"
log "BLOBIO_ROOT=$BLOBIO_ROOT"
cd $BLOBIO_ROOT || die "cd BLOBIO_ROOT failed: exit status=$?"

_P=etc/profile
test -r $_P || die "can not read $_P"

. $_P

log 'dumping process environment ...'
env | while read KV;  do
	log "$KV"
done

BLOBIO_TRUST_FS=${BLOBIO_TRUST_FS:=false}

case "$BLOBIO_SERVICE" in
'')
	die 'env not defined: BLOBIO_SERVICE'
	;;
bio4:*:[1-9]*)
	case "$BLOBIO_BIO4D_PORT" in
	'')
		log 'env BLOBIO_BIO4D_PORT not defined'
		#  extract port from BLOBIO_SERVICE
		BLOBIO_BIO4D_PORT=$(
			echo $BLOBIO_SERVICE				|
			sed 's/.*:\([1-9][0-9]*\)$/\1/'
		)
		log "extracted bio4d port: $BLOBIO_BIO4D_PORT"
		;;
	[1-9]*[0-9])
		log "predefined bio4d port: $BLOBIO_BIO4D_PORT" 
		;;
	*)
		die "unrecognized BLOBIO_BIO4D_PORT: $BLOBIO_BIO4D_PORT"
		;;
	esac
	;;
*)
	die "BLOBIO_SERVICE not bio4: $BLOBIO_SERVICE"
	;;
esac

kill-bio4d

BLOBIO_TRUST_FS=${BLOBIO_TRUST_FS:=false}
log "trust fs: $BLOBIO_TRUST_FS"

BLOBIO_BIO4D_NET_TIMEOUT=${BLOBIO_BIO4D_NET_TIMEOUT:=20}
log "net timeout: ${BLOBIO_BIO4D_NET_TIMEOUT}s"

BLOBIO_BIO4D_RRD_DURATION=${BLOBIO_BIO4D_RRD_DURATION:=0}
log "rrd duration: ${BLOBIO_BIO4D_NET_TIMEOUT}s"

zap_run
log 'invoking sbin/bio4d ...'
sbin/bio4d								\
	--trust-fs $BLOBIO_TRUST_FS					\
	--port $BLOBIO_BIO4D_PORT					\
	--root $BLOBIO_ROOT						\
	--net-timeout $BLOBIO_BIO4D_NET_TIMEOUT				\
	--in-foreground							\
	--ps-title-XXXXXXXXXXXXXXXXXXXXXXX				\
	--rrd-duration $BLOBIO_BIO4D_RRD_DURATION
STATUS=$?
log "sbin/bio4d exit status: $STATUS"
kill-bio4d
