#!/usr/bin/env bash
#
#  Synopsis:
#	Convert file system paths in dirs data/fs_[a-z]* into udigs
#  Usage:
#	fs2udig | xargs bio-eat		#  touch every blob
#  Note:
#	The "find" command should do a "-follow".
#
#	Must have read access to $BLOBIO_ROOT/data.
#	Starting directory must be match <algorithm>_fs
#

PROG=$(basename $0)

die()
{
	echo "$PROG: $@" >&2
	exit 1
}

#
#  Find blob files in directories data/fs_<algorithm>/[0-9a-f]{3}.
#
find_blob() {(
	local FS=$1
	test -d $FS || exit 0

	ALGORITHM=$(echo $FS | sed 's/fs_//')
	cd $FS
	test $(
		find . -maxdepth 1 -type d -name '[0-9a-f][0-9a-f][0-9a-f]' |
		wc -l
	) -gt 0 || exit 0

	#  strip out leading "data/fs_" to get the algorithm
	find [0-9a-f][0-9a-f][0-9a-f] -type f -follow			|
				sed "s/......../$ALGORITHM:/"
)}

test -n "$BLOBIO_ROOT" || die 'environment variable BLOBIO_ROOT not defined'
test -d $BLOBIO_ROOT || die "no data directory: $BLOBIO_ROOT/data"
cd $BLOBIO_ROOT/data || die "cd $BLOBIO_ROOT/data failed"

find . -maxdepth 1 -type d -name 'fs_[a-z]*' -follow			|
	sed 's/..//'							|
	while read FS;  do
		find_blob $FS
	done
