#!/bin/bash
#
#  Synopsis:
#	Wrapper script for foreground execution of bio4d process from launchd
#  Exit Status:
#	0	ok
#	1	error
#  Usage:
#	In  /Library/LaunchDaemons/blobio.bio4d.plist
#
#	<key>ProgramArguments</key>
#	<array>
#	  <string>/usr/local/jmscott/sbin/launchd-log</string>
#	  <string>/usr/local/blobio/sbin/launchd-bio4d</string>
#	</array>
#	...
#	<key>EnvironmentVariables</key>
#	<key>BLOBIO_ROOT</key>
#	<string>/usr/local/blobio</string>
#	<key>BLOBIO_BIO4D_RRD_DURATION</key>
#	<string>60</string>
#	<key>BLOBIO_BIO4D_PORT</key>
#	<string>1797</string>
#  See:
#	$BLOBIO_ROOT/lib/blobio.bio4d.plist.example
#	$BLOBIO_ROOT/etc/profile
#  Note:
#	The full environment is expected to be set in blobio.bio4d.plist
#	and specifically not set in $BLOBIO_ROOT/etc/profile.
#
PROG=$(basename $0)

#  Define defaults for vars specific to daemon bio4d
export	\
      BLOBIO_BIO4D_RRD_DURATION=${BLOBIO_BIO4D_RRD_DURATION:=60}
export BLOBIO_BIO4D_NET_TIMEOUT=${BLOBIO_BIO4D_NET_TIMEOUT:=20}
export BLOBIO_BIO4D_PORT=${BLOBIO_BIO4D_PORT:=1797}

log()
{
	echo "$(date +'%Y/%m/%d: %H:%M:%S'): $PROG: $@"
}

die()
{
	log "ERROR: $@" >&2
	exit 1
}

leave()
{
	log good bye, cruel world
	exit
}

catch_SIG()
{
	log 'caught signal'
	exit 1 
}

log hello, world
trap leave EXIT
trap catch_SIG SIGQUIT SIGTERM

test -n "$BLOBIO_ROOT" || die 'env not defined: BLOBIO_ROOT'
log "cd to BLOBIO_ROOT: $BLOBIO_ROOT"
cd $BLOBIO_ROOT || die "cd failed: exit status=$?"
test -r etc/profile && . etc/profile

log "BLOBIO_ROOT=$BLOBIO_ROOT"
log "PATH=$PATH"
log "bio4d port: $BLOBIO_BIO4D_PORT"
log "stat sample duration: $BLOBIO_BIO4D_RRD_DURATION sec"
log "net timeout: $BLOBIO_BIO4D_NET_TIMEOUT sec"
log "current directory: $(pwd)"

log 'insure bio4d-* processes not running' 
zap-proc run/bio4d.pid							\
	bio4d-arborist							\
	bio4d-brr-logger						\
	bio4d-listen							\
	bio4d-logger							\
	bio4d-request							||
  die "zap-proc failed: exit status=$?"

log 'starting sbin/bio4d'
sbin/bio4d								\
	--ps-title-XXXXXXXXXXXXXXXXXXXXXXX				\
	--in-foreground							\
	--port $BLOBIO_BIO4D_PORT					\
	--root $BLOBIO_ROOT						\
	--net-timeout $BLOBIO_BIO4D_NET_TIMEOUT				\
	--rrd-duration $BLOBIO_BIO4D_RRD_DURATION			||
  die "sbin/bio4d failed: exit status=$?"
