#!/usr/bin/env perl
#
#  Synopsis:
#	Write tuple from round robin database sample in run/bio4d.stat
#  Description:
#	Write a tuple summaring stats written in run/bio4d.stat
#  Usage:
#	run-stat-bio4d path/to/bio4d.brr
#  See:
#	script "run-stat"
#

die 'wrong number of arguments' unless @ARGV == 1;

my $stat_path = $ARGV[0];

my $RRD;
my (
	$boot_connect_count,
	$boot_ok_count,
	$boot_fault_count,
	$sample_ok_count,
	$sample_fault_count
) = (0, 0, 0, 0, 0);

open($RRD, "<$stat_path") or die "open(<run/bio4d.stat) failed: $!";

while (<$RRD>) {
	my (
		$sample_time,
		$success_count,
		$error_count,
		$timeout_count,
		$signal_count,
		$fault_count,
		$get_count,
		$put_count,
		$give_count,
		$take_count,
		$eat_count,
		$wrap_count,
		$roll_count,
		$chat_ok_count,
		$chat_no_count,
		$chat_no2_count,
		$chat_no3_count,
		$eat_no_count,
		$take_no_count,
	) = split(':');

	$boot_ok_count += $success_count;
	$boot_fault_count +=
			$error_count + $timeout_count + $signal_count +
	                $fault_count
	;
	$boot_connect_count += $boot_ok_count + $boot_fault_count;

	$sample_ok_count = $success_count;
	$sample_fault_count =
			$error_count + $timeout_count + $signal_count +
	                $fault_count
	;
	$sample_connect_count = $sample_ok_count + $sample_fault_count;
}

print <<END;
boot	$boot_connect_count	$boot_ok_count	$boot_fault_count
sample	$sample_connect_count	$sample_ok_count	$sample_fault_count
END
