#!/bin/sh
#
#  Synopsis:
#	Merge the bio4d samples in log/bio4d-stat.log into log/bio4d.rrd
#  Usage:
#	* * * * * update-rrd >>log/update-rrd.log 2>&1
#

PROG=$(basename $0)
RRD=log/bio4d.rrd
LOG=log/bio4d-stat.log
TMP_LOG=log/bio4d-stat-$(date +'%s').log

die()
{
	echo "$PROG: ERROR: $@" >&2
	exit 1
}

leave()
{
	rm -f $TMP_LOG
}

trap leave EXIT

test "$BLOBIO_ROOT" || die 'env variable not defined: BLOBIO_ROOT'
cd $BLOBIO_ROOT || die "cd $BLOBIO failed"

#
#  Freeze the stats sample set.
#
#  A minor race condition exists, since writes can stil occur to
#  log/bio4d-stat.log.
#
mv $LOG $TMP_LOG || die "mv $LOG $TMP_LOG failed"

#
#  Slurp up the most recent sample set now frozen in $TMP_LOG
#
xargs rrdupdate $RRD <$TMP_LOG
STATUS=$?
test $STATUS = 0 || die "rrdupdate failed: exit status=$STATUS"

#
#  Record the samples log file for posterity
#
exec bio-put-file $TMP_LOG
