#!/usr/bin/env bash
#
#  Synopsis:
#	Find unresolved blobs in service table, discovered after 'yesterday'
#  Usage:
#	export BLOBIO_ROOT=/opt/jmscott/jmsdesk/blobio
#	LOG=$BLOBIO_ROOT/log/cron-rummy-yesterday.log
#	* * * * * $BLOBIO_ROOT/sbin/cron-rummy-yesterday >>$LOG
#  Depends:
#	GNU date
#	github https://github.com/jmscott/work
#	postgresql
#  Exit Status:
#	0	ok
#	1	error
#  Note:
#	Why not do cron-rummy 'yesterday'?
#
#	Consider detecting if another blob is running and exiting
#	quickly with an empty *.txn record.  We could tag such records
#	cause START_TIME==END_TIME and NO/OK==0.
#

START_TIME=$(RFC3339Nano)		#  Note: need $JMSCOTT_ROOT in PATH
START_EPOCH=$(date +'%s')

RUMMY_UDIG_SET=${TMPDIR:=/tmp}/$(basename $0)-$$.udig
#  store stats for txn log, since 
PSQL='psql --quiet --no-align --no-psqlrc --tuples-only'

log()
{
	echo "$(date +'%Y/%m/%d %H:%M:%S'): $@"
}

die()
{
	log "ERROR: $@" >&2
	exit 1
}

leave()
{
	rm -f $RUMMY_UDIG_SET || log "ERROR: rm -f $RUMMY_UDIG_SET failed" >&2
	log "good bye, cruel world: elapsed $(
		duration-english $(expr $(date +'%s') - $START_EPOCH)
	)"
}

test $# = 0 || die 'wrong number of arguments'
test -n "$BLOBIO_ROOT" || die 'var not defined: BLOBIO_ROOT'

log 'hello, world'
trap leave EXIT

log "BLOBIO_ROOT=$BLOBIO_ROOT"
cd $BLOBIO_ROOT || die "cd $BLOBIO_ROOT failed: exit status=$?"
test -e 
. etc/profile

test -n "$BLOBIO_SERVICE" || die 'env not defined: BLOBIO_SERVICE'
export BLOBIO_GET_SERVICE=${BLOBIO_GET_SERVICE:=fs:$BLOBIO_ROOT}?brr=ff

log "BLOBIO_SERVICE=$BLOBIO_SERVICE"
log "PATH=$PATH"
log "PGHOST=$PGHOST PORT=$PGPORT USER=$PGUSER DATABASE=$PGDATABASE"

log "tmp rummy udig set: $RUMMY_UDIG_SET"
log 'fetching blobs from rummy since yesterday ...'
$PSQL --output $RUMMY_UDIG_SET <<'END'					|| die "psql rummy yeserday failed: exit status=$?"
SELECT
	r.blob
  FROM
  	blobio.rummy r
	  JOIN blobio.brr_discover d ON (d.blob = r.blob)
  WHERE
  	d.start_time >= 'yesterday'
;
END

test -e $RUMMY_UDIG_SET || die 'rummy set file does not exist'

log "rummy blob count: $(wc -l $RUMMY_UDIG_SET | awk '{print $1}')"

#  fetch each blob to trigger merge of row in table brr_blob_size

OK=0
NO=0
while read UDIG;  do
	blobio get							\
		--udig $UDIG						\
		--service $BLOBIO_SERVICE				\
		--output-path /dev/null
	STATUS=$?
	case $STATUS in
	0)
		log ">$UDIG"
		OK=$(($OK + 1))
		;;
	1)
		NO=$(($NO + 1))
		log "?$UDIG"
		;;
	*)
		die "blobio get /dev/null failed: exit status=$STATUS"
		;;
	esac
done <$RUMMY_UDIG_SET

TXN=spool/cron-rummy-yesterday.txn
log "transaction log: $TXN"
echo "$START_TIME	$(RFC3339Nano)	$OK	$NO" >>$TXN		||
	die "echo >txn failed: exit status=$?"

exit 0
