#!/bin/bash
#
#  Synopsis:
#	Report on symmetric difference between the file system and service view.
#  Usage:
#	fs-xor-service >fs-xor-service.log 2>&1 &
#	32 4 * * Sun sbin/fs-xor-service >>support/fs-xor-service/fxs.out 2>&1
#  Note:
#	- The scan of file system kind of assumes either sha or bc160 digests.
#	  In particular, to constuct the udig from the file path, we strip off
#	  the two directories by zapping the first eight chars in the file path:
#
#		fs_sha/797/d4b/797d4b6ca43b699fd27f1b55fca62b50e72db0f5
#
#	- Would be nice display timestamps blobs, to quickly identify
#	  blobs that arrived during scan.
#
#	- Be wary of the LC_COLLATE environment variable.  Setting value to 'C'
#	  forces sorting case sensitive ascii, I (jmscott) think.
#

START_TIME=$(date +%s)
PROG=$(basename $0)

#
#  Force sort command to honor case.
#
export LC_COLLATE=C

log()
{
	echo "$(date +'%Y/%m/%d %H:%M:%S'): $@"
}

die()
{
	log "ERROR: $@" >&2
	exit 1
}

leave()
{
	DURATION=$(expr $(date +%s) - $START_TIME)
	log "$(duration-english $DURATION): good bye, cruel world"
}

log hello, world
trap leave EXIT INT QUIT TERM

test -n "$BLOBIO_ROOT" || die 'BLOBIO_ROOT environment variable not defined'

cd $BLOBIO_ROOT || die "cd $BLOBIO_ROOT failed"
log "BLOBIO_ROOT=$BLOBIO_ROOT"

if [ -r etc/profile ];  then
	. etc/profile
else
	log "WARN: etc/profile does not exist (ok)"
fi

log "PGHOST=$PGHOST"
log "PGPORT=$PGPORT"
log "PGUSER=$PGUSER"
log "PGDATABASE=$PGDATABASE"

log "PATH=$PATH"

log "starting scan of $(pwd)/data/ ..."
log "file system only in column <, service only in column >"
comm -3 <(fs2udig | sort) <(ls-service)					|
	sed 's/^\t/> /' 						|
	sed 's/^\([^>]\)/< \1/'						|
	while read LINE;  do
		log $LINE
	done
log 'done with xor of file system and service table'
