#!/usr/bin/env bash
#
#  Synopsis:
#	Create the schema "blobio" and udig data types as superuser.
#  Description:
#	Create the blobio schema and install the udig data type in a database.
#	The current role of caller must have super user permission to
#	install the udig in blobio.udig in a particular database.  Also,
#	the schema.sql must be readable in the current directory oif invocation.
#  Exit Status:
#	0	ok, schema blobio and udig types installed in db $1
#	1	unexpected failure
#

PROG=$(basename $0)

PSQL='psql
	--tuples-only
	--quiet
	--set ON_ERROR_STOP=1
	--pset format=unaligned
'

ROLE_SQL='
  SELECT
  	current_user
'

IS_SUPER_SQL='
  SELECT
	rolsuper
    FROM
    	pg_roles
    WHERE
    	rolname = current_role
'

DATABASE_OWNER_SQL='
  SELECT
  	datdba::regrole
    FROM
    	pg_database
    WHERE
    	datname = current_database()
'

log()
{
	echo "$PROG: $@"
}

die()
{
	log "ERROR: $@" >&2
	exit 1
}

xsql()
{
	local WHAT=$1
	local SQL=$2

	$PSQL --command "$SQL" || die "psql $WHAT failed: exit status=$?"
}

test $# = 1 || die "bad cli arg count: got $#, want 1"
DATABASE=$1
log "database: $DATABASE"
export PGDATABASE=$1

log "PGHOST=$PGHOST"
log "PGPORT=$PGPORT"
log "PGUSER=$PGUSER"
log "PGDATABASE=$PGDATABASE"

log get current role ...
ROLE=$(xsql role "$ROLE_SQL") || exit 1
log "current role: $ROLE"

log get role super perms ...
IS_SUPER=$($PSQL --command "$IS_SUPER_SQL") || exit 1
log "is super: $IS_SUPER"
test $IS_SUPER = t || die 'must be super user to create udig type'

log get database owner ...
DATABASE_OWNER=$($PSQL --command "$DATABASE_OWNER_SQL") || exit 1
log "database owner: $DATABASE_OWNER"

log get SHAREDIR via pg_config ...
SHAREDIR=$(pg_config --sharedir) || die "pg_config failed: exit status=$?"

UDIG_PATH=$SHAREDIR/contrib/udig.sql
log "udig path: $UDIG_PATH"
test -r $UDIG_PATH || die "can not read udig.sql: $UDIG_PATH"

SCHEMA_PATH=schema.sql
log "schema path: $SCHEMA_PATH"
test -r $SCHEMA_PATH || die "can not read schema.sql"
psql									\
	--set "DBOWNER=$DATABASE_OWNER"					\
	--set "UDIG_PATH=$UDIG_PATH"					\
	--file $SCHEMA_PATH						||
	  die "psql schema failed: exit status=$?"
