#!/bin/bash
#
#  Synopsis:
#	Push bio4d stat samples into the table blobio.bio4d_stat
#  Note:
#	Race condition exists between the time the log file is renamed
#	and the insert into the database.  A slightly safer algorithm
#	would be to sha the frozen log file before and after the put to the db.
#
#		FROZEN=bio4d-stat-<timestamp>.log
#		mv bio4d-stat.log $FROZEN
#		sleep FLUSH_PAUSE
#		SHA1=$(blobio eat $FROZEN)
#		psql <bio4d-stat-<timestamp>.log
#		SHA2=$(blobio eat $FROZEN)
#		test $SHA1 = $SHA2 || die
#

STAT=log/bio4d-stat.log
FLUSH_PAUSE=${BLOBIO_STAT_FLUSH_PAUSE:=5}
MERGE_SQL=lib/merge-bio4d_request_stat.sql
PSQL='psql --no-psqlrc --quiet --pset=pager=off'

log()
{
	echo "$(date +'%Y/%m/%d %H:%M:%S'): #$$: $@"
}

die()
{
	log "ERROR: $@" >&2
	exit 1
}

leave()
{
	log 'good bye, cruel world'
}

log hello, world
trap leave EXIT INT QUIT TERM

#  insure environment BLOBIO environment variables are defined

test -n "$BLOBIO_ROOT" || die 'BLOBIO_ROOT environment variable not defined'
log "BLOBIO_ROOT=$BLOBIO_ROOT"
cd $BLOBIO_ROOT || die "cd $BLOBIO_ROOT failed"

test -e etc/profile || die "missing expected profile: $(pwd)/etc/profile"
. etc/profile

test -n "$BLOBIO_SERVICE" ||
			die 'BLOBIO_SERVICE environment variable not defined'
log "BLOBIO_SERVICE=$BLOBIO_SERVICE"

test -n "$BLOBIO_ALGORITHM" ||
			die 'BLOBIO_ALGORITHM environment variable not defined'
log "BLOBIO_ALGORITHM=$BLOBIO_ALGORITHM"

log "PGHOST=$PGHOST"
log "PGPORT=$PGPORT"
log "PGUSER=$PGUSER"
log "PGPASSWORD=$PGPASSWORD"
log "PGDATABASE=$PGDATABASE"

if [ ! -e $STAT ];  then
	log "WARN: file does not exist: $STAT"
	exit 1
fi
if [ ! -s $STAT ];  then
	log "WARN: file is empty: $RDD"
	exit 2
fi

#  move the sample file to a frozen version

NOW=$(date +'%Y%m%d_%H%M%S')
STAT_FROZEN=$(echo $STAT | sed "s/\.log$/-$NOW.log/")
log "frozen sample file: $STAT_FROZEN"
mv $STAT $STAT_FROZEN || die "mv $STAT $STAT_FROZEN failed"

log "flush pause $FLUSH_PAUSE sec ..."
sleep $FLUSH_PAUSE

log "merging new samples with sql $MERGE_SQL"
$PSQL --file $MERGE_SQL <$STAT_FROZEN || die "psql $MERGE_SQL failed: status=$?"

log "blobify frozen samples: $STAT_FROZEN"
bio-put-file $STAT_FROZEN || die "bio-put-file $STAT_FROZEN failed: status=$?"
bio-give $STAT_FROZEN || die "bio-give $STAT_FROZEN failed: status=$?"
