#!/usr/bin/env bash
#
#  Synopsis:
#	Summarize blobs not in service, udigs sourced from stdin
#  Usage:
#	ls-service | not-in-service
#

PSQL='psql --no-psqlrc --quiet --pset=pager=off'

exec $PSQL --file $BLOBIO_ROOT/lib/not-in-service.sql 
